# Generated by Django 5.2 on 2025-04-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_categoria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
            preserve_default=False,
        ),
    ]
